# Exercise 2.C Working with multiple DataFrames

In [1]:
import numpy as np

In [2]:
import pandas as pd

## Basic Aggregations

In [5]:
data = {'Product': ['A', 'B', 'C', 'A', 'B', 'C', 'A', 'B', 'C'],
'Region': ['North', 'South', 'East', 'West', 'North', 'South', 'East',
'West', 'North'],
'Units_Sold': [10, 15, 20, 5, 10, 15, 10, 5, 15],
'Price': [100, 200, 150, 100, 200, 150, 100, 200, 150]}

In [6]:
df_sales = pd.DataFrame(data)

In [7]:
df_sales['Revenue'] = df_sales['Units_Sold'] * df_sales['Price']

In [8]:
df_sales

  Product Region  Units_Sold  Price  Revenue
0       A  North          10    100     1000
1       B  South          15    200     3000
2       C   East          20    150     3000
3       A   West           5    100      500
4       B  North          10    200     2000
5       C  South          15    150     2250
6       A   East          10    100     1000
7       B   West           5    200     1000
8       C  North          15    150     2250

In [10]:
total_units = df_sales['Units_Sold'].sum()
total_revenue = df_sales['Revenue'].sum()

In [12]:
print("Total Units Sold:", total_units)
print("Total Revenue:", total_revenue)

Total Units Sold: 105
Total Revenue: 16000

In [13]:
avg_units = df_sales['Units_Sold'].mean()
avg_revenue = df_sales['Revenue'].mean()

In [14]:
print("Average Units Sold:", avg_units)
print("Average Revenue:",avg_revenue)

Average Units Sold: 11.666666666666666
Average Revenue: 1777.7777777777778

## Grouping Data

In [16]:
product_group = df_sales.groupby('Product')[['Units_Sold','Revenue']].sum()
product_group

         Units_Sold  Revenue
Product
A                25     2500
B                30     6000
C                50     7500

In [17]:
region_group = df_sales.groupby('Region')[['Units_Sold','Revenue']].mean()
region_group

        Units_Sold  Revenue
Region
East     15.000000   2000.0
North    11.666667   1750.0
South    15.000000   2625.0
West      5.000000    750.0

In [19]:
product_region_group = df_sales.groupby(['Product','Region'])[['Units_Sold','Revenue']].sum()
product_region_group

                Units_Sold  Revenue
Product Region
A       East            10     1000
        North           10     1000
        West             5      500
B       North           10     2000
        South           15     3000
        West             5     1000
C       East            20     3000
        North           15     2250
        South           15     2250

## Merging DataFrames

In [20]:
product_data = {'Product': ['A', 'B', 'C'],
'Category': ['Electronics', 'Furniture', 'Appliances']}

In [21]:
df_products = pd.DataFrame(product_data)

In [23]:
df_merged = pd.merge(df_sales, df_products, on='Product')
df_merged

  Product Region  Units_Sold  Price  Revenue     Category
0       A  North          10    100     1000  Electronics
1       B  South          15    200     3000    Furniture
2       C   East          20    150     3000   Appliances
3       A   West           5    100      500  Electronics
4       B  North          10    200     2000    Furniture
5       C  South          15    150     2250   Appliances
6       A   East          10    100     1000  Electronics
7       B   West           5    200     1000    Furniture
8       C  North          15    150     2250   Appliances

In [25]:
category_revenue = df_merged.groupby('Category')['Revenue'].sum()
category_revenue

Category
Appliances     7500
Electronics    2500
Furniture      6000
Name: Revenue, dtype: int64